get_model:
	wget https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8n.pt
	mkdir -p venv/ 
	python3 -m venv venv && . venv/bin/activate && pip install -r requirements.txt && python3 export_model.py
