pub mod by_scalar;
pub mod erf;
pub mod gelu;
pub mod hardswish;
pub mod leaky_relu;
pub mod lut;
pub mod mmm;
pub mod reduce;
pub mod rms_norm;
pub mod rounding;
pub mod sigmoid;
pub mod silu;
pub mod tanh;
pub mod unicast;

pub use self::by_scalar::{HMulByScalar8, SMulByScalar4};
pub use self::erf::SErf4;
pub use self::gelu::{HGelu8, SGelu4};
pub use self::hardswish::{HHardSwish8, SHardSwish4};
pub use self::leaky_relu::{HLeakyRelu8, SLeakyRelu4};
pub use self::lut::GenericLut8;
pub use self::rounding::{ScaleShiftAndRound, Scaler};
pub use self::sigmoid::{HSigmoid8, SSigmoid4};
pub use self::silu::{HSiLU8, SSiLU4};
pub use self::tanh::{HTanh8, STanh4};

submit_routine!(F32, Sigmoid, sigmoid::SSigmoid4);
submit_routine!(F16, Sigmoid, sigmoid::HSigmoid8);
submit_routine!(F32, Tanh, tanh::STanh4);
submit_routine!(F16, Tanh, tanh::HTanh8);
submit_routine!(F32, Silu, silu::SSiLU4);
submit_routine!(F16, Silu, silu::HSiLU8);
submit_routine!(F32, Gelu, gelu::SGelu4);
submit_routine!(F16, Gelu, gelu::HGelu8);
submit_routine!(F32, Erf, erf::SErf4);
submit_routine!(F32, Hardswish, hardswish::SHardSwish4);
submit_routine!(F16, Hardswish, hardswish::HHardSwish8);
submit_routine!(F32Param, LeakyRelu, leaky_relu::SLeakyRelu4);
submit_routine!(F16Param, LeakyRelu, leaky_relu::HLeakyRelu8);
submit_routine!(RmsNormF32, RmsNorm, "generic", rms_norm::rms_norm_f32);
submit_routine!(LutU8, Lut, lut::GenericLut8);
