pub mod by_scalar;
pub mod erf;
pub mod gelu;
pub mod hardswish;
pub mod leaky_relu;
pub mod lut;
pub mod mmm;
pub mod reduce;
pub mod rms_norm;
pub mod rounding;
pub mod sigmoid;
pub mod silu;
pub mod tanh;
pub mod unicast;

pub use self::by_scalar::{HMulByScalar8, SMulByScalar4};
pub use self::erf::SErf4;
pub use self::gelu::{HGelu8, SGelu4};
pub use self::hardswish::{HHardSwish8, SHardSwish4};
pub use self::leaky_relu::{HLeakyRelu8, SLeakyRelu4};
pub use self::lut::GenericLut8;
pub use self::rounding::{ScaleShiftAndRound, Scaler};
pub use self::sigmoid::{HSigmoid8, SSigmoid4};
pub use self::silu::{HSiLU8, SSiLU4};
pub use self::tanh::{HTanh8, STanh4};

routine!(F32, Sigmoid, sigmoid::SSigmoid4);
routine!(F16, Sigmoid, sigmoid::HSigmoid8);
routine!(F32, Tanh, tanh::STanh4);
routine!(F16, Tanh, tanh::HTanh8);
routine!(F32, Silu, silu::SSiLU4);
routine!(F16, Silu, silu::HSiLU8);
routine!(F32, Gelu, gelu::SGelu4);
routine!(F16, Gelu, gelu::HGelu8);
routine!(F32, Erf, erf::SErf4);
routine!(F32, Hardswish, hardswish::SHardSwish4);
routine!(F16, Hardswish, hardswish::HHardSwish8);
routine!(F32Param, LeakyRelu, leaky_relu::SLeakyRelu4);
routine!(F16Param, LeakyRelu, leaky_relu::HLeakyRelu8);
routine!(F32Param, MulByScalar, by_scalar::SMulByScalar4);
routine!(F16Param, MulByScalar, by_scalar::HMulByScalar8);
routine!(F32Reduce, ReduceMax, reduce::max::SMax4);
routine!(F16Reduce, ReduceMax, reduce::max::HMax8);
routine!(F32Reduce, ReduceMin, reduce::min::SMin4);
routine!(F32Reduce, ReduceSum, reduce::sum::SSum4);
routine!(F16Reduce, ReduceSum, reduce::sum::HSum8);
routine!(F32MapReduce, Softmax2, reduce::softmax_l2::SSoftMaxL2Accurate);
routine!(RmsNormF32, RmsNorm, "generic", rms_norm::rms_norm_f32);
routine!(LutU8, Lut, lut::GenericLut8);

routine!(BinF32, BinByScalar(Mul), by_scalar::SMulByScalar4);
routine!(BinF32, BinByScalar(Add), by_scalar::SAddByScalar4);
routine!(BinF32, BinByScalar(Sub), by_scalar::SSubByScalar4);
routine!(BinF32, BinByScalar(SubF), by_scalar::SSubFByScalar4);
routine!(BinF32, BinByScalar(Min), by_scalar::SMinByScalar4);
routine!(BinF32, BinByScalar(Max), by_scalar::SMaxByScalar4);
routine!(BinF32, BinUnicast(Mul), unicast::SUnicastMul4);
routine!(BinF32, BinUnicast(Add), unicast::SUnicastAdd4);
routine!(BinF32, BinUnicast(Sub), unicast::SUnicastSub4);
routine!(BinF32, BinUnicast(SubF), unicast::SUnicastSubF4);
routine!(BinF32, BinUnicast(Min), unicast::SUnicastMin4);
routine!(BinF32, BinUnicast(Max), unicast::SUnicastMax4);
