// Generated by `tract cost-model regen` — do not hand-edit.
// platform: intel_avx512   cpu: 11th Gen Intel(R) Core(TM) i9-11900KB @ 3.30GHz
// date: 2026-07-17T17:30:20Z
// tract: 0.23.5-pre (git 467dabab3)
// validation over 80 shapes: current picker regret 1.0693x -> linear 1.0021x
use crate::frame::mmm::LinearCostModel;

pub fn linear_model() -> LinearCostModel<'static> {
    LinearCostModel {
        default_kernel: "avx512_mmm_f32_64x3",
        kernels: &[
            "avx512_mmm_f32_128x1",
            "avx512_mmm_f32_16x1",
            "avx512_mmm_f32_16x12",
            "avx512_mmm_f32_16x8",
            "avx512_mmm_f32_32x5",
            "avx512_mmm_f32_32x6",
            "avx512_mmm_f32_48x4",
            "avx512_mmm_f32_64x3",
            "avx512_mmm_f32_80x2",
            "fma_mmm_f32_16x5",
            "fma_mmm_f32_16x6",
            "fma_mmm_f32_24x4",
            "fma_mmm_f32_32x1",
            "fma_mmm_f32_32x3",
            "fma_mmm_f32_40x2",
            "fma_mmm_f32_64x1",
            "fma_mmm_f32_8x8",
        ],
        coeffs: &[
            [9.807558e-11, 0e0, 0e0],
            [1.0761914e-10, 0e0, 0e0],
            [2.0211765e-11, 0e0, 0e0],
            [2.3976286e-11, 0e0, 0e0],
            [2.8493749e-11, 0e0, 0e0],
            [2.596049e-11, 0e0, 0e0],
            [3.1648528e-11, 0e0, 0e0],
            [3.760886e-11, 0e0, 0e0],
            [5.2868054e-11, 0e0, 0e0],
            [3.8255916e-11, 0e0, 0e0],
            [3.3364696e-11, 0e0, 0e0],
            [4.066426e-11, 0e0, 0e0],
            [1.0912237e-10, 0e0, 0e0],
            [4.7952108e-11, 0e0, 0e0],
            [6.206697e-11, 0e0, 0e0],
            [1.06253645e-10, 0e0, 0e0],
            [2.9447878e-11, 0e0, 0e0],
        ],
        restream: 0e0,
    }
}
