// Generated by `tract cost-model regen` — do not hand-edit.
// platform: amd_avx512   cpu: AMD Ryzen 9 9950X3D 16-Core Processor
// user: kali   date: 2026-07-16T13:12:05Z
// tract: 0.23.5-pre (git f09f1efe0)
// validation over 272 shapes: current picker regret 1.0834x -> linear 1.0052x
use crate::frame::mmm::LinearCostModel;

pub fn linear_model() -> LinearCostModel<'static> {
    LinearCostModel {
        default_kernel: "avx512_mmm_f32_64x3",
        kernels: &[
            "avx512_mmm_f32_128x1",
            "avx512_mmm_f32_16x12",
            "avx512_mmm_f32_16x8",
            "avx512_mmm_f32_32x5",
            "avx512_mmm_f32_32x6",
            "avx512_mmm_f32_48x4",
            "avx512_mmm_f32_64x3",
            "avx512_mmm_f32_80x2",
            "fma_mmm_f32_16x5",
            "fma_mmm_f32_16x6",
            "fma_mmm_f32_24x4",
            "fma_mmm_f32_32x1",
            "fma_mmm_f32_32x3",
            "fma_mmm_f32_40x2",
            "fma_mmm_f32_64x1",
            "fma_mmm_f32_8x8",
        ],
        coeffs: &[
            [2.0288805e-11, 2.6815146e-8, 5.1281437e-5],
            [8.356944e-12, 3.8864254e-8, 4.874376e-8],
            [8.92717e-12, 2.858623e-8, 2.8480028e-7],
            [7.857317e-12, 3.4698605e-8, 1.8035228e-6],
            [7.5709135e-12, 3.8271533e-8, 1.4504687e-6],
            [7.860135e-12, 3.810854e-8, 3.7589791e-6],
            [8.365647e-12, 3.3602756e-8, 1.4272163e-5],
            [1.0656748e-11, 5.5880157e-8, 1.7345797e-5],
            [1.5519688e-11, 1.8319668e-8, 2.1851701e-8],
            [1.492743e-11, 2.1962085e-8, 5.965787e-7],
            [1.4938871e-11, 2.2752213e-8, 0e0],
            [3.0350358e-11, 5.7347185e-9, 1.207495e-5],
            [1.4915574e-11, 2.2093637e-8, 1.6750291e-6],
            [1.6045328e-11, 2.2279728e-8, 2.7743167e-6],
            [2.181627e-11, 1.5385089e-8, 4.3076267e-5],
            [1.7292367e-11, 1.9890784e-8, 0e0],
        ],
    }
}
