// Generated by `tract cost-model regen` — do not hand-edit.
// platform: amd_fma   cpu: AMD Ryzen 7 PRO 4750G with Radeon Graphics
// user: kali   host: salombo   date: 2026-07-16T12:49:21Z
// tract: 0.23.5-pre (git f09f1efe0)
// validation over 272 shapes: current picker regret 1.3607x -> linear 1.0131x
use crate::frame::mmm::LinearCostModel;

pub fn linear_model() -> LinearCostModel<'static> {
    LinearCostModel {
        default_kernel: "fma_mmm_f32_32x3",
        kernels: &[
            "fma_mmm_f32_16x5",
            "fma_mmm_f32_16x6",
            "fma_mmm_f32_24x4",
            "fma_mmm_f32_32x1",
            "fma_mmm_f32_32x3",
            "fma_mmm_f32_40x2",
            "fma_mmm_f32_64x1",
            "fma_mmm_f32_8x8",
        ],
        coeffs: &[
            [1.7393633e-11, 5.4208584e-8, 4.3249156e-7],
            [1.7168173e-11, 6.183843e-8, 0e0],
            [1.824883e-11, 4.721221e-8, 3.5210574e-6],
            [5.0682594e-11, 2.5149092e-7, 0e0],
            [2.0359037e-11, 2.9046967e-8, 8.429983e-6],
            [2.4587832e-11, 0e0, 3.4700275e-5],
            [5.188204e-11, 2.525001e-7, 1.105488e-4],
            [2.0534153e-11, 4.6251206e-8, 0e0],
        ],
    }
}
