// Generated by `tract cost-model regen` — do not hand-edit.
// platform: intel_fma   cpu: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
// date: 2026-07-16T14:33:07Z
// tract: 0.23.5-pre
// validation over 272 shapes: current picker regret 1.0295x -> linear 1.0095x
use crate::frame::mmm::LinearCostModel;

pub fn linear_model() -> LinearCostModel<'static> {
    LinearCostModel {
        default_kernel: "fma_mmm_f32_32x3",
        kernels: &[
            "fma_mmm_f32_16x5",
            "fma_mmm_f32_16x6",
            "fma_mmm_f32_24x4",
            "fma_mmm_f32_32x1",
            "fma_mmm_f32_32x3",
            "fma_mmm_f32_40x2",
            "fma_mmm_f32_64x1",
            "fma_mmm_f32_8x8",
        ],
        coeffs: &[
            [1.9576639e-11, 0e0, 1.1206573e-5],
            [1.8056955e-11, 4.2759214e-9, 1.1735802e-5],
            [2.1245533e-11, 0e0, 1.1231028e-5],
            [5.8360976e-11, 0e0, 0e0],
            [2.5449524e-11, 0e0, 5.155286e-6],
            [3.2265024e-11, 0e0, 1.8036377e-5],
            [5.4269218e-11, 0e0, 5.648757e-5],
            [2.0132026e-11, 1.8346459e-8, 3.6403496e-6],
        ],
        restream: 2.3364435e-11,
    }
}
