// Generated by `tract cost-model regen` — do not hand-edit.
// platform: intel_avx512   cpu: (forced)
// user: ubuntu   date: 2026-07-16T20:59:08Z
// tract: 0.23.5-pre (git 546124dd1)
// validation over 269 shapes: current picker regret 1.0350x -> linear 1.0273x
use crate::frame::mmm::LinearCostModel;

pub fn linear_model() -> LinearCostModel<'static> {
    LinearCostModel {
        default_kernel: "avx512_mmm_f32_64x3",
        kernels: &[
            "avx512_mmm_f32_128x1",
            "avx512_mmm_f32_16x12",
            "avx512_mmm_f32_16x8",
            "avx512_mmm_f32_32x5",
            "avx512_mmm_f32_32x6",
            "avx512_mmm_f32_48x4",
            "avx512_mmm_f32_64x3",
            "avx512_mmm_f32_80x2",
            "fma_mmm_f32_16x5",
            "fma_mmm_f32_16x6",
            "fma_mmm_f32_24x4",
            "fma_mmm_f32_32x1",
            "fma_mmm_f32_32x3",
            "fma_mmm_f32_40x2",
            "fma_mmm_f32_64x1",
            "fma_mmm_f32_8x8",
        ],
        coeffs: &[
            [2.8409091e-11, 0e0, 1.5589166e-4],
            [1.4872525e-11, 7.4577464e-8, 0e0],
            [1.5149694e-11, 6.294855e-8, 0e0],
            [1.6240183e-11, 5.9677525e-8, 0e0],
            [1.5903856e-11, 7.137147e-8, 0e0],
            [1.6957151e-11, 5.5827403e-8, 0e0],
            [1.8484759e-11, 4.645628e-8, 0e0],
            [2.0303127e-11, 6.5729187e-9, 3.414374e-5],
            [1.6618349e-11, 4.8114927e-8, 0e0],
            [1.6317687e-11, 4.715993e-8, 0e0],
            [1.8078001e-11, 2.745405e-8, 0e0],
            [4.8055494e-11, 2.3481328e-9, 0e0],
            [2.101819e-11, 1.805949e-8, 0e0],
            [2.6023054e-11, 4.3969917e-9, 0e0],
            [4.3888327e-11, 0e0, 0e0],
            [1.8591875e-11, 4.0398533e-8, 0e0],
        ],
        restream: 1.2408923e-12,
    }
}
