pub mod binary;
pub mod broadcast;
pub mod cast;
pub mod change_axes;
pub mod element_wise;
pub mod gemm;
pub mod konst;
pub mod reduce;
pub mod slice;
pub mod softmax;
pub mod sync;

pub use binary::MetalBinOp;
pub use broadcast::MetalMultiBroadcastTo;
pub use cast::MetalCast;
pub use change_axes::{MetalAxisOp, MetalIntoShape};
pub use element_wise::MetalElementWiseOp;
pub use gemm::MetalGemm;
pub use konst::MetalConst;
pub use reduce::MetalReduce;
pub use slice::MetalSlice;
pub use softmax::MetalSoftmax;
pub use sync::MetalSync;
