[package]
name = "activations"
version = "0.1.0"
edition = "2021"

[workspace]
members = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.4.0"
proptest = "1.1.0"

[dependencies]


[[bench]]
name = "vm"
harness = false
