[package]
name = "face_similarity_arcface_onnx"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
clap = { version = "4.5.9", features = ["derive"] }
image.workspace = true 
tract-onnx.workspace = true
tract-core.workspace = true

