// Generated by `tract cost-model regen` — do not hand-edit.
// platform: cortex_a7   cpu: ARMv7 Processor rev 3 (v7l)
// date: 2026-07-17T17:47:33Z
// tract: 0.23.5-pre
// validation over 36 shapes: current picker regret 1.0004x -> linear 1.0031x
use crate::frame::mmm::LinearCostModel;

pub fn linear_model() -> LinearCostModel<'static> {
    LinearCostModel {
        default_kernel: "armv7neon_mmm_f32_8x6_generic",
        kernels: &[
            "armv7neon_mmm_f32_32x1_cortexa7",
            "armv7neon_mmm_f32_32x1_cortexa9",
            "armv7neon_mmm_f32_32x1_generic",
            "armv7neon_mmm_f32_8x1_generic",
            "armv7neon_mmm_f32_8x4_cortexa7",
            "armv7neon_mmm_f32_8x4_cortexa9",
            "armv7neon_mmm_f32_8x4_generic",
            "armv7neon_mmm_f32_8x6_cortexa7",
            "armv7neon_mmm_f32_8x6_cortexa9",
            "armv7neon_mmm_f32_8x6_generic",
        ],
        coeffs: &[
            [1.5368065e-9, 3.004327e-7, 1.2703205e-6],
            [1.6503982e-9, 3.120771e-7, 1.2908918e-6],
            [1.7416373e-9, 3.0267273e-7, 1.0059667e-6],
            [2.0166966e-9, 2.8888527e-7, 1.0519947e-6],
            [1.0829506e-9, 5.5748535e-7, 1.6015783e-6],
            [1.1075889e-9, 5.601286e-7, 1.5072782e-6],
            [1.0996574e-9, 5.4615407e-7, 1.2843658e-6],
            [9.972734e-10, 5.486439e-7, 1.5976844e-6],
            [1.0140543e-9, 5.4476084e-7, 1.6143154e-6],
            [1.012184e-9, 5.3697676e-7, 1.3612033e-6],
        ],
        restream: 0e0,
    }
}
