// Generated by `tract cost-model regen` — do not hand-edit.
// platform: cortex_a7   cpu: ARMv7 Processor rev 3 (v7l)
// date: 2026-07-16T16:56:18Z
// tract: 0.23.5-pre
// validation over 227 shapes: current picker regret 1.0150x -> linear 1.0119x
use crate::frame::mmm::LinearCostModel;

pub fn linear_model() -> LinearCostModel<'static> {
    LinearCostModel {
        default_kernel: "armv7neon_mmm_f32_8x6_generic",
        kernels: &[
            "armv7neon_mmm_f32_32x1_cortexa7",
            "armv7neon_mmm_f32_32x1_cortexa9",
            "armv7neon_mmm_f32_32x1_generic",
            "armv7neon_mmm_f32_8x1_generic",
            "armv7neon_mmm_f32_8x4_cortexa7",
            "armv7neon_mmm_f32_8x4_cortexa9",
            "armv7neon_mmm_f32_8x4_generic",
            "armv7neon_mmm_f32_8x6_cortexa7",
            "armv7neon_mmm_f32_8x6_cortexa9",
            "armv7neon_mmm_f32_8x6_generic",
        ],
        coeffs: &[
            [2.358771e-9, 0e0, 0e0],
            [2.4038398e-9, 0e0, 0e0],
            [2.63956e-9, 0e0, 0e0],
            [2.7103022e-9, 1.6456787e-7, 0e0],
            [1.3589725e-9, 2.7785512e-7, 0e0],
            [1.4101642e-9, 2.3441332e-7, 0e0],
            [2.5812041e-9, 0e0, 0e0],
            [1.2186382e-9, 3.1301494e-7, 0e0],
            [1.2247628e-9, 3.283357e-7, 0e0],
            [2.1503057e-9, 0e0, 0e0],
        ],
        restream: 0e0,
    }
}
