// Generated by `tract cost-model regen` — do not hand-edit.
// platform: cortex_a9   cpu: ARMv7 Processor rev 10 (v7l)
// date: 2026-07-17T17:50:09Z
// tract: 0.23.5-pre
// validation over 36 shapes: current picker regret 1.0858x -> linear 1.0000x
use crate::frame::mmm::LinearCostModel;

pub fn linear_model() -> LinearCostModel<'static> {
    LinearCostModel {
        default_kernel: "armv7neon_mmm_f32_8x6_generic",
        kernels: &[
            "armv7neon_mmm_f32_32x1_cortexa7",
            "armv7neon_mmm_f32_32x1_cortexa9",
            "armv7neon_mmm_f32_32x1_generic",
            "armv7neon_mmm_f32_8x1_generic",
            "armv7neon_mmm_f32_8x4_cortexa7",
            "armv7neon_mmm_f32_8x4_cortexa9",
            "armv7neon_mmm_f32_8x4_generic",
            "armv7neon_mmm_f32_8x6_cortexa7",
            "armv7neon_mmm_f32_8x6_cortexa9",
            "armv7neon_mmm_f32_8x6_generic",
        ],
        coeffs: &[
            [2.7568363e-9, 3.36097e-7, 1.9963595e-7],
            [2.3473936e-9, 6.8262224e-8, 0e0],
            [3.715417e-9, 0e0, 0e0],
            [4.0768318e-9, 1.5258387e-7, 0e0],
            [1.209754e-9, 6.241918e-7, 1.5367328e-6],
            [8.698204e-10, 6.1211716e-7, 1.3312181e-6],
            [1.3068701e-9, 4.245877e-7, 0e0],
            [1.0398751e-9, 5.43976e-7, 1.4077355e-6],
            [7.7258056e-10, 5.428761e-7, 1.3314509e-6],
            [1.0347576e-9, 4.2044732e-7, 1.9907782e-8],
        ],
        restream: 0e0,
    }
}
