// Generated by `tract cost-model regen` — do not hand-edit.
// platform: cortex_a9   cpu: ARMv7 Processor rev 10 (v7l)
// date: 2026-07-16T16:56:21Z
// tract: 0.23.5-pre
// validation over 227 shapes: current picker regret 1.0007x -> linear 1.0005x
use crate::frame::mmm::LinearCostModel;

pub fn linear_model() -> LinearCostModel<'static> {
    LinearCostModel {
        default_kernel: "armv7neon_mmm_f32_8x6_generic",
        kernels: &[
            "armv7neon_mmm_f32_32x1_cortexa7",
            "armv7neon_mmm_f32_32x1_cortexa9",
            "armv7neon_mmm_f32_32x1_generic",
            "armv7neon_mmm_f32_8x1_generic",
            "armv7neon_mmm_f32_8x4_cortexa7",
            "armv7neon_mmm_f32_8x4_cortexa9",
            "armv7neon_mmm_f32_8x4_generic",
            "armv7neon_mmm_f32_8x6_cortexa7",
            "armv7neon_mmm_f32_8x6_cortexa9",
            "armv7neon_mmm_f32_8x6_generic",
        ],
        coeffs: &[
            [3.5185248e-9, 0e0, 0e0],
            [3.212245e-9, 0e0, 0e0],
            [4.553206e-9, 0e0, 0e0],
            [4.255692e-9, 2.7069701e-8, 0e0],
            [1.228173e-9, 5.361867e-7, 0e0],
            [9.158042e-10, 4.911403e-7, 0e0],
            [1.5475748e-9, 0e0, 0e0],
            [1.0450972e-9, 6.4495083e-7, 0e0],
            [7.941577e-10, 6.231035e-7, 0e0],
            [1.4287171e-9, 0e0, 0e0],
        ],
        restream: 0e0,
    }
}
