// Generated by `tract cost-model regen` — do not hand-edit.
// platform: apple_m4   cpu: Apple M4
// date: 2026-07-17T07:16:14Z
// tract: 0.23.5-pre (git a41d66f4b)
// validation over 272 shapes: current picker regret 1.0775x -> linear 1.0775x
use crate::frame::mmm::LinearCostModel;

pub fn linear_model() -> LinearCostModel<'static> {
    LinearCostModel {
        default_kernel: "sme_mmm_f32_32x32",
        kernels: &[
            "apple_amx_mmm_f32_32x1",
            "apple_amx_mmm_f32_32x32",
            "arm64simd_mmm_f32_12x8_a53",
            "arm64simd_mmm_f32_12x8_a55",
            "arm64simd_mmm_f32_12x8_gen",
            "arm64simd_mmm_f32_16x4_a53",
            "arm64simd_mmm_f32_16x4_a55",
            "arm64simd_mmm_f32_16x4_gen",
            "arm64simd_mmm_f32_24x4_a53",
            "arm64simd_mmm_f32_24x4_a55",
            "arm64simd_mmm_f32_24x4_gen",
            "arm64simd_mmm_f32_32x1_gen",
            "arm64simd_mmm_f32_32x3_gen",
            "arm64simd_mmm_f32_64x1_a53",
            "arm64simd_mmm_f32_64x1_a55",
            "arm64simd_mmm_f32_64x1_gen",
            "arm64simd_mmm_f32_8x8_a53",
            "arm64simd_mmm_f32_8x8_a55",
            "arm64simd_mmm_f32_8x8_gen",
            "sme_mmm_f32_32x32",
            "sme_mmv_f32_64x1",
        ],
        coeffs: &[
            [2.2558415e-11, 2.626561e-7, 0e0],
            [1.9005927e-12, 1.3993458e-6, 0e0],
            [2.5109883e-11, 2.1235842e-8, 1.5451848e-6],
            [2.1489156e-11, 2.3660947e-8, 4.2634284e-7],
            [1.5836669e-11, 2.36298e-8, 4.773855e-7],
            [3.193549e-11, 1.8773191e-8, 1.4302842e-6],
            [3.1087882e-11, 1.6358916e-8, 8.572383e-7],
            [1.6400091e-11, 1.7530011e-8, 1.06667855e-7],
            [3.1754883e-11, 2.5033025e-8, 1.823555e-6],
            [3.1161622e-11, 2.0608566e-8, 0e0],
            [1.5919977e-11, 2.3608289e-8, 0e0],
            [3.345833e-11, 1.2729329e-9, 2.5210777e-5],
            [1.5824257e-11, 2.5000984e-8, 5.594849e-7],
            [6.2755905e-11, 7.196945e-9, 2.3888206e-6],
            [4.6619163e-11, 1.10863185e-8, 0e0],
            [4.0157114e-11, 0e0, 1.4258491e-6],
            [3.2329587e-11, 1.5733717e-8, 8.0827914e-7],
            [1.9791025e-11, 1.9598748e-8, 6.32572e-7],
            [1.7046706e-11, 1.6746514e-8, 1.9318286e-7],
            [1.2648359e-12, 2.9379703e-7, 3.985781e-6],
            [1.6882669e-11, 7.8586304e-8, 0e0],
        ],
        restream: 3.2931203e-12,
    }
}
