// Generated by `tract cost-model regen` — do not hand-edit.
// platform: apple_m1   cpu: Apple M1 Max
// user: mathieu.poumeyrol   date: 2026-07-16T14:24:01Z
// tract: 0.23.5-pre (git 324416bfd)
// validation over 272 shapes: current picker regret 1.3742x -> linear 1.0635x
use crate::frame::mmm::LinearCostModel;

pub fn linear_model() -> LinearCostModel<'static> {
    LinearCostModel {
        default_kernel: "apple_amx_mmm_f32_32x32",
        kernels: &[
            "apple_amx_mmm_f32_32x1",
            "apple_amx_mmm_f32_32x32",
            "arm64simd_mmm_f32_12x8_a53",
            "arm64simd_mmm_f32_12x8_a55",
            "arm64simd_mmm_f32_12x8_gen",
            "arm64simd_mmm_f32_16x4_a53",
            "arm64simd_mmm_f32_16x4_a55",
            "arm64simd_mmm_f32_16x4_gen",
            "arm64simd_mmm_f32_24x4_a53",
            "arm64simd_mmm_f32_24x4_a55",
            "arm64simd_mmm_f32_24x4_gen",
            "arm64simd_mmm_f32_32x1_gen",
            "arm64simd_mmm_f32_32x3_gen",
            "arm64simd_mmm_f32_64x1_a53",
            "arm64simd_mmm_f32_64x1_a55",
            "arm64simd_mmm_f32_64x1_gen",
            "arm64simd_mmm_f32_8x8_a53",
            "arm64simd_mmm_f32_8x8_a55",
            "arm64simd_mmm_f32_8x8_gen",
        ],
        coeffs: &[
            [3.470368e-11, 2.6694798e-7, 0e0],
            [2.132909e-12, 1.4978468e-6, 0e0],
            [3.450403e-11, 1.2242403e-8, 4.8579827e-6],
            [2.8835902e-11, 2.8536464e-8, 0e0],
            [1.9722626e-11, 3.048093e-8, 0e0],
            [4.3589916e-11, 3.8233794e-9, 1.08337545e-5],
            [3.9496923e-11, 2.2017616e-8, 0e0],
            [2.0026373e-11, 2.3139945e-8, 4.3837355e-7],
            [4.2917073e-11, 0e0, 2.2650322e-5],
            [3.953409e-11, 2.741017e-8, 0e0],
            [1.9899875e-11, 3.14955e-8, 0e0],
            [4.347741e-11, 0e0, 4.5173863e-5],
            [2.0022964e-11, 2.8960946e-8, 7.332666e-7],
            [9.132465e-11, 0e0, 0e0],
            [6.672845e-11, 0e0, 0e0],
            [4.9007173e-11, 0e0, 0e0],
            [4.475174e-11, 9.100461e-9, 0e0],
            [2.5814097e-11, 2.3762501e-8, 0e0],
            [2.0034327e-11, 2.4686237e-8, 0e0],
        ],
    }
}
