// Generated by `tract cost-model regen` — do not hand-edit.
// platform: cortex_a53   cpu: 0xd03
// date: 2026-07-17T17:38:08Z
// tract: 0.23.5-pre
// validation over 52 shapes: current picker regret 1.0473x -> linear 1.0519x
use crate::frame::mmm::LinearCostModel;

pub fn linear_model() -> LinearCostModel<'static> {
    LinearCostModel {
        default_kernel: "arm64simd_mmm_f32_32x3_gen",
        kernels: &[
            "arm64simd_mmm_f32_12x8_a53",
            "arm64simd_mmm_f32_12x8_a55",
            "arm64simd_mmm_f32_12x8_gen",
            "arm64simd_mmm_f32_16x4_a53",
            "arm64simd_mmm_f32_16x4_a55",
            "arm64simd_mmm_f32_16x4_gen",
            "arm64simd_mmm_f32_24x4_a53",
            "arm64simd_mmm_f32_24x4_a55",
            "arm64simd_mmm_f32_24x4_gen",
            "arm64simd_mmm_f32_32x1_gen",
            "arm64simd_mmm_f32_32x3_gen",
            "arm64simd_mmm_f32_64x1_a53",
            "arm64simd_mmm_f32_64x1_a55",
            "arm64simd_mmm_f32_64x1_gen",
            "arm64simd_mmm_f32_8x8_a53",
            "arm64simd_mmm_f32_8x8_a55",
            "arm64simd_mmm_f32_8x8_gen",
        ],
        coeffs: &[
            [2.795097e-10, 3.3931784e-7, 6.6477816e-7],
            [4.42675e-10, 1.1740394e-7, 0e0],
            [3.6567788e-10, 1.471672e-7, 0e0],
            [3.6722864e-10, 3.6601884e-7, 0e0],
            [4.853041e-10, 1.1241782e-7, 0e0],
            [4.849731e-10, 1.471761e-7, 0e0],
            [3.3990644e-10, 5.166184e-7, 0e0],
            [4.6024362e-10, 3.6141725e-7, 0e0],
            [4.80736e-10, 3.4804074e-8, 0e0],
            [1.7822834e-9, 0e0, 0e0],
            [6.275011e-10, 0e0, 0e0],
            [1.1534866e-9, 0e0, 0e0],
            [2.0268607e-9, 0e0, 0e0],
            [1.6299577e-9, 0e0, 0e0],
            [3.1634556e-10, 2.956225e-7, 5.452617e-7],
            [4.404975e-10, 1.2561881e-7, 0e0],
            [4.1536927e-10, 1.2967645e-7, 0e0],
        ],
        restream: 0e0,
    }
}
