// Generated by `tract cost-model regen` — do not hand-edit.
// platform: cortex_a53   cpu: 0xd03
// date: 2026-07-16T15:36:12Z
// tract: 0.23.5-pre
// validation over 311 shapes: current picker regret 1.0037x -> linear 1.0009x
use crate::frame::mmm::LinearCostModel;

pub fn linear_model() -> LinearCostModel<'static> {
    LinearCostModel {
        default_kernel: "arm64simd_mmm_f32_32x3_gen",
        kernels: &[
            "arm64simd_mmm_f32_12x8_a53",
            "arm64simd_mmm_f32_12x8_a55",
            "arm64simd_mmm_f32_12x8_gen",
            "arm64simd_mmm_f32_16x4_a53",
            "arm64simd_mmm_f32_16x4_a55",
            "arm64simd_mmm_f32_16x4_gen",
            "arm64simd_mmm_f32_24x4_a53",
            "arm64simd_mmm_f32_24x4_a55",
            "arm64simd_mmm_f32_24x4_gen",
            "arm64simd_mmm_f32_32x1_gen",
            "arm64simd_mmm_f32_32x3_gen",
            "arm64simd_mmm_f32_64x1_a53",
            "arm64simd_mmm_f32_64x1_a55",
            "arm64simd_mmm_f32_64x1_gen",
            "arm64simd_mmm_f32_8x8_a53",
            "arm64simd_mmm_f32_8x8_a55",
            "arm64simd_mmm_f32_8x8_gen",
        ],
        coeffs: &[
            [2.8207145e-10, 5.859334e-7, 0e0],
            [4.5867135e-10, 4.3606292e-7, 0e0],
            [3.8602282e-10, 4.318994e-7, 0e0],
            [3.7181394e-10, 3.7162545e-7, 0e0],
            [4.7478826e-10, 3.2174336e-7, 0e0],
            [4.825415e-10, 3.1376825e-7, 0e0],
            [3.4215872e-10, 4.7207325e-7, 0e0],
            [4.5257548e-10, 5.596107e-7, 0e0],
            [4.8317333e-10, 3.3518722e-7, 0e0],
            [1.6063467e-9, 0e0, 0e0],
            [6.5014943e-10, 2.7273488e-8, 0e0],
            [1.1969893e-9, 0e0, 0e0],
            [1.8325613e-9, 0e0, 0e0],
            [1.717112e-9, 0e0, 0e0],
            [3.197513e-10, 4.006281e-7, 0e0],
            [4.5387485e-10, 3.111394e-7, 0e0],
            [4.315911e-10, 3.0625472e-7, 0e0],
        ],
        restream: 0e0,
    }
}
