// Generated by `tract cost-model regen` — do not hand-edit.
// platform: cortex_a55   cpu: 0xd05
// user: root   date: 2026-07-16T15:33:21Z
// tract: 0.23.5-pre
// validation over 311 shapes: current picker regret 1.0477x -> linear 1.0092x
use crate::frame::mmm::LinearCostModel;

pub fn linear_model() -> LinearCostModel<'static> {
    LinearCostModel {
        default_kernel: "arm64simd_mmm_f32_32x3_gen",
        kernels: &[
            "arm64simd_mmm_f32_12x8_a53",
            "arm64simd_mmm_f32_12x8_a55",
            "arm64simd_mmm_f32_12x8_gen",
            "arm64simd_mmm_f32_16x4_a53",
            "arm64simd_mmm_f32_16x4_a55",
            "arm64simd_mmm_f32_16x4_gen",
            "arm64simd_mmm_f32_24x4_a53",
            "arm64simd_mmm_f32_24x4_a55",
            "arm64simd_mmm_f32_24x4_gen",
            "arm64simd_mmm_f32_32x1_gen",
            "arm64simd_mmm_f32_32x3_gen",
            "arm64simd_mmm_f32_64x1_a53",
            "arm64simd_mmm_f32_64x1_a55",
            "arm64simd_mmm_f32_64x1_gen",
            "arm64simd_mmm_f32_8x8_a53",
            "arm64simd_mmm_f32_8x8_a55",
            "arm64simd_mmm_f32_8x8_gen",
        ],
        coeffs: &[
            [2.0663878e-10, 3.129229e-7, 0e0],
            [1.7690283e-10, 3.6212484e-7, 0e0],
            [2.1720152e-10, 3.9253027e-7, 0e0],
            [2.9017996e-10, 1.4547335e-7, 0e0],
            [2.3863866e-10, 1.8111712e-7, 0e0],
            [2.853406e-10, 2.531493e-7, 0e0],
            [2.605783e-10, 2.2945895e-7, 0e0],
            [2.7847827e-10, 1.0751241e-7, 0e0],
            [2.8633143e-10, 3.1000462e-7, 0e0],
            [7.855437e-10, 0e0, 0e0],
            [3.477515e-10, 2.5755304e-7, 0e0],
            [8.019018e-10, 0e0, 0e0],
            [7.380584e-10, 0e0, 0e0],
            [7.7927703e-10, 0e0, 0e0],
            [2.2260506e-10, 2.218372e-7, 0e0],
            [1.9925044e-10, 2.3050548e-7, 0e0],
            [2.3722702e-10, 2.6867997e-7, 0e0],
        ],
    }
}
