// Generated by `tract cost-model regen` — do not hand-edit.
// platform: cortex_a55   cpu: 0xd05
// date: 2026-07-17T17:44:00Z
// tract: 0.23.5-pre
// validation over 52 shapes: current picker regret 1.0334x -> linear 1.0079x
use crate::frame::mmm::LinearCostModel;

pub fn linear_model() -> LinearCostModel<'static> {
    LinearCostModel {
        default_kernel: "arm64simd_mmm_f32_32x3_gen",
        kernels: &[
            "arm64simd_mmm_f32_12x8_a53",
            "arm64simd_mmm_f32_12x8_a55",
            "arm64simd_mmm_f32_12x8_gen",
            "arm64simd_mmm_f32_16x4_a53",
            "arm64simd_mmm_f32_16x4_a55",
            "arm64simd_mmm_f32_16x4_gen",
            "arm64simd_mmm_f32_24x4_a53",
            "arm64simd_mmm_f32_24x4_a55",
            "arm64simd_mmm_f32_24x4_gen",
            "arm64simd_mmm_f32_32x1_gen",
            "arm64simd_mmm_f32_32x3_gen",
            "arm64simd_mmm_f32_64x1_a53",
            "arm64simd_mmm_f32_64x1_a55",
            "arm64simd_mmm_f32_64x1_gen",
            "arm64simd_mmm_f32_8x8_a53",
            "arm64simd_mmm_f32_8x8_a55",
            "arm64simd_mmm_f32_8x8_gen",
        ],
        coeffs: &[
            [2.1257168e-10, 1.8478737e-7, 0e0],
            [1.798137e-10, 1.9891955e-7, 0e0],
            [2.2325657e-10, 2.2389216e-7, 0e0],
            [3.0537062e-10, 9.7297594e-8, 0e0],
            [2.403643e-10, 1.8614696e-7, 0e0],
            [2.8665287e-10, 2.048659e-7, 0e0],
            [2.568101e-10, 1.8796273e-7, 0e0],
            [2.8843916e-10, 0e0, 0e0],
            [2.81778e-10, 2.3991507e-7, 0e0],
            [8.06941e-10, 0e0, 0e0],
            [3.4047992e-10, 2.1451791e-7, 0e0],
            [7.1618295e-10, 0e0, 0e0],
            [7.4668893e-10, 0e0, 0e0],
            [7.8413565e-10, 0e0, 0e0],
            [2.3102478e-10, 1.8694665e-7, 0e0],
            [1.9609259e-10, 1.9044448e-7, 6.0064224e-8],
            [2.3089831e-10, 2.0644576e-7, 6.038289e-7],
        ],
        restream: 0e0,
    }
}
