[package]
name = "tract-nnef-cli"
version = "0.21.8-pre"
authors = [
	"Mathieu Poumeyrol <kali@zoy.org>",
	"Hubert de La Jonquière <hubert.delajonquiere@sonos.com>"
]
license = "MIT OR Apache-2.0"
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
repository = "https://github.com/snipsco/tract"
keywords = [ "NeuralNetworks", "NNEF" ]
categories = [ "science" ]
autobenches = false
edition = "2021"
rust-version = "1.75"

[dependencies]
anyhow.workspace = true
env_logger.workspace = true
log.workspace = true
structopt.workspace = true
tract-nnef.workspace = true
tract-pulse.workspace = true
tract-onnx-opl.workspace = true
