# vim: set syntax=Dockerfile:

FROM tensorflow/tensorflow:nightly-devel

RUN apt-get update ; apt-get upgrade -y
RUN apt-get install -y crossbuild-essential-arm64
COPY linux_makefile.inc /tensorflow/tensorflow/lite/tools/make/targets/linux_makefile.inc

WORKDIR /tensorflow
RUN ./tensorflow/lite/tools/make/download_dependencies.sh

