name: Sanitized build tests

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 * * MON'

env:
  CARGO_INCREMENTAL: false
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

permissions:
  contents: read

jobs:
  sanitizer-address:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macOS-latest ]

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Rustup update
      run: rustup update
    - name: Run sanitized tests
      run: .travis/asan.sh
