name: Sanitized build tests

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 * * MON'

env:
  CARGO_INCREMENTAL: false
  CARGO_NET_RETRY: 10
  CARGO_HTTP_MULTIPLEXING: false
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

permissions:
  contents: read

jobs:
  sanitizer-address:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macOS-latest ]

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: Rustup update
      run: rustup update
    - name: Run sanitized tests
      run: .travis/asan.sh
