name: Rust crates

on:
  pull_request:
  schedule:
    - cron:  '0 3 * * *'
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: false
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      os: ${{steps.set-matrix.outputs.os}}
      rust: ${{steps.set-matrix.outputs.rust}}

    steps:
      - id: set-matrix
        env:
          FULL: $((github.event.workflow_dispatch || github.event.schedule ))
        run: |
          if [ "$FULL" == "true" ]
          then
            echo 'os=["ubuntu-latest", "macos-latest"]' >> $GITHUB_OUTPUT
            echo 'rust=["1.89.0", "stable", "beta", "nightly"]' >> $GITHUB_OUTPUT
          else
            echo ::notice::Skipping macOS checks on PR and commit. Dispatch workflow manually if needed.
            echo 'os=["ubuntu-latest"]' >> $GITHUB_OUTPUT
            echo 'rust=["1.89.0"]' >> $GITHUB_OUTPUT
          fi

  crates:
    name: ${{matrix.os}} / ${{matrix.crate}} / ${{matrix.rust}}
    needs: prepare-matrix
    strategy:
      matrix:
        os: ${{fromJson(needs.prepare-matrix.outputs.os)}}
        rust: ${{fromJson(needs.prepare-matrix.outputs.rust)}}
        crate: [  tract-data, tract-linalg, tract-core, tract-nnef, tract-hir, tract-onnx,
                  tract-pulse, tract-onnx-opl, tract-pulse-opl, tract-rs,
                  test-unit-core, test-onnx-core, test-nnef-cycle,
               ]
      fail-fast: false

    runs-on: ${{matrix.os}}
    env:
      RUSTUP_TOOLCHAIN: ${{matrix.rust}}

    steps:
    - uses: actions/checkout@v4

    - name: Cargo test
      run: cargo test -p ${{matrix.crate}}

  cuda:
    runs-on: cuda-lovelace
    strategy:
      matrix:
        rust: ${{fromJson(needs.prepare-matrix.outputs.rust)}}
      fail-fast: false
    env:
      RUSTUP_TOOLCHAIN: ${{matrix.rust}}
    steps:
    - uses: actions/checkout@v4

    - name: Cargo test
      run: cargo test -p tract-cuda -p test-cuda

  metal:
    runs-on: macOS
    strategy:
      matrix:
        rust: ${{fromJson(needs.prepare-matrix.outputs.rust)}}
      fail-fast: false
    env:
      RUSTUP_TOOLCHAIN: ${{matrix.rust}}
    steps:
    - uses: actions/checkout@v4

    - name: Cargo test
      run: cargo test -p tract-metal -p test-metal
   
  pedantic:
    name: fmt, clippy, etc (${{matrix.os}} / ${{matrix.rust}})
    needs: prepare-matrix
    strategy:
      matrix:
        os: ${{fromJson(needs.prepare-matrix.outputs.os)}}
        rust: ${{fromJson(needs.prepare-matrix.outputs.rust)}}
      fail-fast: false
    runs-on: ${{matrix.os}}
    env:
      RUSTUP_TOOLCHAIN: ${{matrix.rust}}
    steps:
    - uses: actions/checkout@v4
    - run: cargo check --all-targets
    - run: rustup component add clippy && cargo clippy
    - name: fmt
      run: rustup component add rustfmt && cargo fmt --check
    - name: Warnings
      env:
        RUST_FLAGS: -D warnings
      run: cargo check

  cargo-deny:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-deny
      run: |
        curl -L https://github.com/EmbarkStudios/cargo-deny/releases/download/$VERSION/cargo-deny-$VERSION-x86_64-unknown-linux-musl.tar.gz \
            | tar -zx --strip-components=1 "cargo-deny-$VERSION-x86_64-unknown-linux-musl/cargo-deny"
      env:
          VERSION: 0.18.9
    - name: Run cargo-deny
      run: .travis/cargo-deny-check.sh


