name: Rust crates

on:
  pull_request:
  schedule:
    - cron:  '0 3 * * *'
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: false
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
  what-to-run:
    runs-on: ubuntu-latest
    outputs:
      os: ${{steps.set-matrix.outputs.os}}

    steps:
      - id: set-matrix
        env:
          MACOS: $((github.event.workflow_dispatch || github.event.schedule ))
        run: |
          if [ "$MACOS" == "true" ]
          then
            echo 'os=["ubuntu-latest", "macos-latest"]' >> $GITHUB_OUTPUT
          else
            echo ::notice::Skipping macOS checks on PR and commit. Dispatch workflow manually if needed.
            echo 'os=["ubuntu-latest"]' >> $GITHUB_OUTPUT
          fi

  crates:
    name: ${{matrix.os}} / ${{matrix.crate}}
    needs: what-to-run
    strategy:
      matrix:
        os: ${{fromJson(needs.what-to-run.outputs.os)}}
        crate: [  tract-data, tract-linalg, tract-core, tract-nnef, tract-hir, tract-onnx,
                  tract-pulse, tract-onnx-opl, tract-pulse-opl, tract-rs,
                  test-unit-core, test-onnx-core, test-nnef-cycle,
               ]
      fail-fast: false

    runs-on: ${{matrix.os}}
    permissions:
      id-token: write
      contents: read
    env:
      RUSTUP_TOOLCHAIN: ${{matrix.rust}}
      RUST_BACKTRACE: full

    steps:
    - uses: actions/checkout@v4

    - name: Cargo test
      run: cargo test -p ${{matrix.crate}}

  cuda:
    runs-on: cuda-lovelace
    steps:
    - uses: actions/checkout@v4

    - name: Cargo test
      run: cargo test -p tract-cuda -p test-cuda

  metal:
    runs-on: macOS
    steps:
    - uses: actions/checkout@v4

    - name: Cargo test
      run: cargo test -p tract-metal test-metal
