name: Examples

on:
  schedule:
    - cron:  '0 3 * * *'
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: false
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
  RUSTUP_TOOLCHAIN: 1.89.0

jobs:
  examples:
    runs-on: ubuntu-latest
    outputs:
      examples: ${{steps.set-matrix.outputs.examples}}

    steps:
      - uses: actions/checkout@v6
      - id: set-matrix
        run: |
          echo examples=`find examples -name ci.sh | cut -d/ -f 2 | jq -Rsc '. / "\n" - [""]'` >> "$GITHUB_OUTPUT"

  example:
    name: ${{ matrix.ex }}
    runs-on: ubuntu-latest
    needs: examples
    strategy:
      fail-fast: false
      matrix:
        ex: ${{fromJSON(needs.examples.outputs.examples)}}

    steps:
    - uses: actions/checkout@v6

    - name: Configure AWS Credentials
      # if: github.repository == 'sonos/tract'
      continue-on-error: true
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: arn:aws:iam::567805100031:role/github-runner-tract-ci
        aws-region: us-east-2

    - name: example tests
      env:
        AWS_EC2_METADATA_DISABLED: true
      timeout-minutes: 30
      run: |
        cd examples/${{matrix.ex}}
        ./ci.sh

  build-tract-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cargo build -p tract-cli --profile opt-no-lto
      - uses: actions/upload-artifact@v7
        with:
          name: tract-cli-x86_64
          path: ./target/opt-no-lto/tract

  gpu-examples:
    runs-on: ubuntu-latest
    outputs:
      examples: ${{steps.set-matrix.outputs.examples}}

    steps:
      - uses: actions/checkout@v6
      - id: set-matrix
        run: |
          echo examples=`find examples -name ci-gpu.sh | cut -d/ -f 2 | jq -Rsc '. / "\n" - [""]'` >> "$GITHUB_OUTPUT"

  gpu-example:
    name: ${{ matrix.ex }} (GPU)
    runs-on: cuda-lovelace
    needs: [gpu-examples, build-tract-cli]
    strategy:
      fail-fast: false
      matrix:
        ex: ${{fromJSON(needs.gpu-examples.outputs.examples)}}

    steps:
    - uses: actions/checkout@v6

    - uses: actions/download-artifact@v8
      with:
        name: tract-cli-x86_64
        path: target/opt-no-lto

    - run: chmod +x target/opt-no-lto/tract

    - name: GPU example tests
      timeout-minutes: 60
      run: |
        cd examples/${{matrix.ex}}
        ./ci-gpu.sh
