on:
  push:
    tags:
    - 'v*'

name: Create release

env:
  CARGO_INCREMENTAL: false
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Extract version tag
        id: version
        run: echo value=$(echo ${{ github.ref }} | cut -f 3 -d / | sed 's/^v//' ) >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: tract ${{ steps.version.outputs.value }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_RELEASE }}

