name: Python wheels

on:
  schedule:
    - cron:  '0 3 * * MON'
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      publish:
        description: force publish to pypi
        type: boolean
      pypi_version_override:
        description: override version id detection
        type: string


env:
  CARGO_INCREMENTAL: false
  PYPI_VERSION_OVERRIDE: ${{ inputs.pypi_version_override }}
  CIBW_ENVIRONMENT_PASS_LINUX: "PYPI_VERSION_OVERRIDE"
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
  MACOSX_DEPLOYMENT_TARGET: 10.13

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-14]

    steps:
      - uses: actions/checkout@v6
        
      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@stable

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install rust toolchains
        if: startsWith(matrix.os, 'macOS')
        run: rustup target install x86_64-apple-darwin aarch64-apple-darwin

      - name: Build wheels
        uses: nick-fields/retry@v4
        with:
          max_attempts: 1
          timeout_seconds: 54000 # 15 hours :/
          command: uvx cibuildwheel --output-dir wheelhouse api/py

      - uses: actions/upload-artifact@v7
        with:
          name: wheels-${{github.run_id}}-${{matrix.os}}
          path: ./wheelhouse/*.whl

  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Build SDist
      run: cd api/py && uv build --sdist

    - uses: actions/upload-artifact@v7
      with:
        name: wheels-${{github.run_id}}-src
        path: api/py/dist/*.tar.gz

  upload_all:
    needs: [build_wheels, make_sdist]
    runs-on: ubuntu-latest
    if: (github.event_name == 'release' && github.event.action == 'published') || inputs.publish

    steps:
    - uses: actions/download-artifact@v8
      with:
        pattern: wheels-${{github.run_id}}-*
        merge-multiple: true
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.14.0
      with:
        user: __token__
        password: ${{ secrets.PYPI }}
        verbose: true
